baseURL = "/"
languageCode = "en-us"
title = "Michael Chow"
theme = "hucore"
copyright = "Follow on <a href=\"https://twitter.com/chowthedog\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
pluralizelisttitles = false

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "\\.qmd$", "\\.ipynb$", "\\.py$", "_cache$"]

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
tag = "tags"
category = "categories"

[services]
  [services.googleAnalytics]
     ID = "G-2Z9YSMMH3Y"

[params]
description = "Michael Chow's prod ready data thoughts (and other things)."
keywords = []
author = "Michael Chow"
sharingicons = false
mainSections = ["posts"]



[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/machow"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/chowthedog"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/michael-a-chow/"
fa_icon = "fa-linkedin-square"

[[params.socialshare]]
url = "https://linkedin.com/in/michael-a-chow"
fa_icon = "fa-linkedin-square"

